backend:
  name: github
  repo: smanalorkecil/web-sekolah # Ganti dengan nama repositori GitHub kamu (contoh: smanalorkecil/web-sekolah)
  branch: main # Mengarah ke branch main

# Konfigurasi integrasi Cloudinary
media_library:
  name: cloudinary
  config:
    cloud_name: qi797bcl
    api_key: "334214273144456"

collections:
  - name: "berita"
    label: "Berita & Pengumuman"
    folder: "src/content/berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Berita", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - {
          label: "Kategori",
          name: "category",
          widget: "select",
          options: ["Akademik", "Kesiswaan", "Prestasi", "Pengumuman"],
        }
      - {
          label: "Foto Utama",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Ringkasan Singkat", name: "description", widget: "text" }
      - { label: "Isi Berita", name: "body", widget: "markdown" }
